### ISSUE TITLE
トップページのデザイン修正(PC)

### ISSUE THREAD

**Issue by toshi-ue** [toshi-ue/shuukatu#1]
- [x] メニュー
- [x] サイドバー

メインコンテンツ
  - [x] ジャンルのカード化
  - <del>[ ] ジャンルのスライドショー機能の追加</del>
  - [x] アイテムのカード化

追加修正項目
- [x] サイドバーの全項目追加
- [x] controllerによるサイドバーの全項目抽出

**Comment by toshi-ue** [comment]
h2タグにcolorプロパティが適用されない
```css
h2.title{
  color: #333333;
  // color: red;
  font-size: 25px;
  font-weight: normal;
}
```
